# configuration for connecting kafka broker by clients
# change the values based on your need and brokers
KAFKA:
    # BOOTSTRAP_SERVERS: 192.168.99.100:9092 # change if your brokers live else where
    BOOTSTRAP_SERVERS: wn0-xtvkaf.phpziwd1d3iedoucfn5brcnrrc.ax.internal.cloudapp.net:9092,wn1-xtvkaf.phpziwd1d3iedoucfn5brcnrrc.ax.internal.cloudapp.net:9092
TOPICS:
    TOPICS: test 
    MSG: test99
    MSG_SIZE: 100
    MSG_COUNT: 99

